
/*
 * generated by Xtext
 */
package org.eclipse.iee.translator.jmole.math.generator;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.TreeMap;

import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.emf.ecore.xmi.impl.XMIResourceImpl;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.generator.JavaIoFileSystemAccess;
import org.eclipse.xtext.util.CancelIndicator;
import org.eclipse.xtext.validation.CheckMode;
import org.eclipse.xtext.validation.IResourceValidator;
import org.eclipse.xtext.validation.Issue;

import com.google.inject.Inject;
import com.google.inject.Injector;
import com.google.inject.Provider;

public class Mole {
	
	public static void main(String[] args) {
		//if (args.length==0) {
		//	System.err.println("Aborting: no path to EMF resource provided!");
		//	return;
		//}
		Injector injector = new org.eclipse.iee.translator.jmole.math.MathStandaloneSetupGenerated().createInjectorAndDoEMFRegistration();
		Mole main = injector.getInstance(Mole.class);
		//main.runGenerator(args[0]);
		System.out.println(main.translateMath("1 / (a + b)-c+2.5-6+3.77"));
	}
	
	public static Mole create() {
		Injector injector = new org.eclipse.iee.translator.jmole.math.MathStandaloneSetupGenerated().createInjectorAndDoEMFRegistration();
		return injector.getInstance(Mole.class);
		//main.runGenerator(args[0]);
		//System.out.println(main.translateMath("1 / (a + b)"));
	}
	
	@Inject 
	private Provider<ResourceSet> resourceSetProvider;
	
	@Inject
	private IResourceValidator validator;
	
	@Inject
	private IGenerator generator;
	
	@Inject 	
	private JavaIoFileSystemAccess fileAccess;

	public String translateMath(String input) {
		InputStream inputStream = new ByteArrayInputStream(input.getBytes());
		ResourceSet set = resourceSetProvider.get();
		Resource resource = set.getResource(URI.createURI("test.math"), true);
	
		try {
			resource.unload();
			resource.load(inputStream, set.getLoadOptions());
				
			return ((MathGenerator)generator).generateText(resource);
			
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}
	
	protected void runGenerator(String string) {
		// load the resource
		ResourceSet set = resourceSetProvider.get();
		Resource resource = set.getResource(URI.createURI(string), true);
						
		// validate the resource
		List<Issue> list = validator.validate(resource, CheckMode.ALL, CancelIndicator.NullImpl);
		if (!list.isEmpty()) {
			for (Issue issue : list) {
				System.err.println(issue);
			}
			return;
		}
		
		// configure and start the generator
		fileAccess.setOutputPath("src-gen/");
		//generator.doGenerate(resource, fileAccess);
		
		System.out.println(
			((MathGenerator)generator).generateText(resource)
		);
		
		System.out.println("Code generation finished.");
	}
}
