/*
* generated by Xtext
*/

package org.eclipse.iee.translator.jmole.math.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MathGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class FormulaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Formula");
		private final Assignment cExpressionAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cExpressionExpressionParserRuleCall_0 = (RuleCall)cExpressionAssignment.eContents().get(0);
		
		//Formula:
		//	expression=Expression;
		public ParserRule getRule() { return rule; }

		//expression=Expression
		public Assignment getExpressionAssignment() { return cExpressionAssignment; }

		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_0() { return cExpressionExpressionParserRuleCall_0; }
	}

	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final RuleCall cPrimaryExpressionParserRuleCall_0_0 = (RuleCall)cGroup_0.eContents().get(0);
		private final Action cPlusLeftAction_0_1 = (Action)cGroup_0.eContents().get(1);
		private final Keyword cPlusSignKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cRightAssignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final RuleCall cRightExpressionParserRuleCall_0_3_0 = (RuleCall)cRightAssignment_0_3.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final RuleCall cPrimaryExpressionParserRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Action cMultLeftAction_1_1 = (Action)cGroup_1.eContents().get(1);
		private final Keyword cAsteriskKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cRightAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cRightExpressionParserRuleCall_1_3_0 = (RuleCall)cRightAssignment_1_3.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final RuleCall cPrimaryExpressionParserRuleCall_2_0 = (RuleCall)cGroup_2.eContents().get(0);
		private final Action cPowBaseAction_2_1 = (Action)cGroup_2.eContents().get(1);
		private final Keyword cCircumflexAccentKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cPowerAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cPowerExpressionParserRuleCall_2_3_0 = (RuleCall)cPowerAssignment_2_3.eContents().get(0);
		private final RuleCall cPrimaryExpressionParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Expression:
		//	PrimaryExpression {Plus.left=current} "+" right=Expression | PrimaryExpression {Mult.left=current} "*"
		//	right=Expression | PrimaryExpression {Pow.base=current} "^" power=Expression | PrimaryExpression;
		public ParserRule getRule() { return rule; }

		//PrimaryExpression {Plus.left=current} "+" right=Expression | PrimaryExpression {Mult.left=current} "*" right=Expression
		//| PrimaryExpression {Pow.base=current} "^" power=Expression | PrimaryExpression
		public Alternatives getAlternatives() { return cAlternatives; }

		//PrimaryExpression {Plus.left=current} "+" right=Expression
		public Group getGroup_0() { return cGroup_0; }

		//PrimaryExpression
		public RuleCall getPrimaryExpressionParserRuleCall_0_0() { return cPrimaryExpressionParserRuleCall_0_0; }

		//{Plus.left=current}
		public Action getPlusLeftAction_0_1() { return cPlusLeftAction_0_1; }

		//"+"
		public Keyword getPlusSignKeyword_0_2() { return cPlusSignKeyword_0_2; }

		//right=Expression
		public Assignment getRightAssignment_0_3() { return cRightAssignment_0_3; }

		//Expression
		public RuleCall getRightExpressionParserRuleCall_0_3_0() { return cRightExpressionParserRuleCall_0_3_0; }

		//PrimaryExpression {Mult.left=current} "*" right=Expression
		public Group getGroup_1() { return cGroup_1; }

		//PrimaryExpression
		public RuleCall getPrimaryExpressionParserRuleCall_1_0() { return cPrimaryExpressionParserRuleCall_1_0; }

		//{Mult.left=current}
		public Action getMultLeftAction_1_1() { return cMultLeftAction_1_1; }

		//"*"
		public Keyword getAsteriskKeyword_1_2() { return cAsteriskKeyword_1_2; }

		//right=Expression
		public Assignment getRightAssignment_1_3() { return cRightAssignment_1_3; }

		//Expression
		public RuleCall getRightExpressionParserRuleCall_1_3_0() { return cRightExpressionParserRuleCall_1_3_0; }

		//PrimaryExpression {Pow.base=current} "^" power=Expression
		public Group getGroup_2() { return cGroup_2; }

		//PrimaryExpression
		public RuleCall getPrimaryExpressionParserRuleCall_2_0() { return cPrimaryExpressionParserRuleCall_2_0; }

		//{Pow.base=current}
		public Action getPowBaseAction_2_1() { return cPowBaseAction_2_1; }

		//"^"
		public Keyword getCircumflexAccentKeyword_2_2() { return cCircumflexAccentKeyword_2_2; }

		//power=Expression
		public Assignment getPowerAssignment_2_3() { return cPowerAssignment_2_3; }

		//Expression
		public RuleCall getPowerExpressionParserRuleCall_2_3_0() { return cPowerExpressionParserRuleCall_2_3_0; }

		//PrimaryExpression
		public RuleCall getPrimaryExpressionParserRuleCall_3() { return cPrimaryExpressionParserRuleCall_3; }
	}

	public class PrimaryExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PrimaryExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cExpressionParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cNumberLiteralAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cValueAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Keyword cValue1Keyword_1_1_0 = (Keyword)cValueAssignment_1_1.eContents().get(0);
		
		////	 Addition | Multiplication | Power;
		////Addition returns Expression:
		////Multiplication returns Expression:
		////Power returns Expression:
		////	PrimaryExpression {Pow.base=current} '^' power=Expression;
		//PrimaryExpression returns Expression:
		//	"(" Expression ")" | {NumberLiteral} value="1";
		public ParserRule getRule() { return rule; }

		//"(" Expression ")" | {NumberLiteral} value="1"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"(" Expression ")"
		public Group getGroup_0() { return cGroup_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }

		//Expression
		public RuleCall getExpressionParserRuleCall_0_1() { return cExpressionParserRuleCall_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_0_2() { return cRightParenthesisKeyword_0_2; }

		//{NumberLiteral} value="1"
		public Group getGroup_1() { return cGroup_1; }

		//{NumberLiteral}
		public Action getNumberLiteralAction_1_0() { return cNumberLiteralAction_1_0; }

		//value="1"
		public Assignment getValueAssignment_1_1() { return cValueAssignment_1_1; }

		//"1"
		public Keyword getValue1Keyword_1_1_0() { return cValue1Keyword_1_1_0; }
	}
	
	
	private FormulaElements pFormula;
	private ExpressionElements pExpression;
	private PrimaryExpressionElements pPrimaryExpression;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public MathGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Formula:
	//	expression=Expression;
	public FormulaElements getFormulaAccess() {
		return (pFormula != null) ? pFormula : (pFormula = new FormulaElements());
	}
	
	public ParserRule getFormulaRule() {
		return getFormulaAccess().getRule();
	}

	//Expression:
	//	PrimaryExpression {Plus.left=current} "+" right=Expression | PrimaryExpression {Mult.left=current} "*"
	//	right=Expression | PrimaryExpression {Pow.base=current} "^" power=Expression | PrimaryExpression;
	public ExpressionElements getExpressionAccess() {
		return (pExpression != null) ? pExpression : (pExpression = new ExpressionElements());
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}

	////	 Addition | Multiplication | Power;
	////Addition returns Expression:
	////Multiplication returns Expression:
	////Power returns Expression:
	////	PrimaryExpression {Pow.base=current} '^' power=Expression;
	//PrimaryExpression returns Expression:
	//	"(" Expression ")" | {NumberLiteral} value="1";
	public PrimaryExpressionElements getPrimaryExpressionAccess() {
		return (pPrimaryExpression != null) ? pPrimaryExpression : (pPrimaryExpression = new PrimaryExpressionElements());
	}
	
	public ParserRule getPrimaryExpressionRule() {
		return getPrimaryExpressionAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
