/*
* generated by Xtext
*/
package org.eclipse.iee.translator.jmole.math.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MathAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/iee/translator/jmole/math/parser/antlr/internal/InternalMath.tokens");
	}
}
