/*
 * generated by Xtext
 */
package org.eclipse.iee.translator.molex.mex;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MexRuntimeModule extends org.eclipse.iee.translator.molex.mex.AbstractMexRuntimeModule {

}
