/*
 * generated by Xtext
 */
package org.eclipse.iee.translator.Jmole.math;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MathRuntimeModule extends org.eclipse.iee.translator.Jmole.math.AbstractMathRuntimeModule {

}
