/*
* generated by Xtext
*/
package org.eclipse.iee.translator.molex.mex.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MexAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/iee/translator/molex/mex/parser/antlr/internal/InternalMex.tokens");
	}
}
